drop table TG_SETTING;
create table TG_SETTING(
	category1 int,
	category2 int,
	category3 int,
	value1 VARCHAR(100) not null,
	value2 VARCHAR(100),
	value3 VARCHAR(100),
	value4 VARCHAR(100),
	value5 VARCHAR(100),
        primary key(category1,category2,category3))
	default character set utf8 collate utf8_unicode_ci;
    
    INSERT TG_SETTING VALUE(1,1,1,'株式会社ブライトスター','BRIGHT STAR CO., LTD.','http://www.brightstar.co.jp','星川','一輝');
INSERT TG_SETTING VALUE(1,1,2,'332-0016','東京都新宿区高田馬場4-13-10','カワイビル2F','','');
INSERT TG_SETTING VALUE(1,1,3,'03-5332-8898','03-5332-8897','info1@brightstar.co.jp','呉','艶');
INSERT TG_SETTING VALUE(1,1,4,'見積書Temp.xlsx','請求書Temp.xlsx','注文書Temp.xlsx','','');
INSERT TG_SETTING VALUE(1,2,1,'株式会社トップクラウド','TOP CLOUD CO., LTD.','http://www.geocities.jp/kk_topcloud/','星川','一輝');
INSERT TG_SETTING VALUE(1,2,2,'332-0016','東京都新宿区高田馬場4-13-10','カワイビル2F','','');
INSERT TG_SETTING VALUE(1,2,3,'03-5332-8898','03-5332-8897','kk_topcloud@yahoo.co.jp','呉','艶');
INSERT TG_SETTING VALUE(1,2,4,'見積書Temp2.xlsx','請求書Temp2.xlsx','注文書Temp2.xlsx','','');
INSERT TG_SETTING VALUE(2,1,1,'\\\\192.168.11.88\\会社共有（it）\\社内管理','','','','');
INSERT TG_SETTING VALUE(2,1,2,'受注管理','','','','');
INSERT TG_SETTING VALUE(2,1,3,'外注発行','','','','');
INSERT TG_SETTING VALUE(2,1,4,'請求作成','','','','');
INSERT TG_SETTING VALUE(2,1,5,'見積作成','','','','');
INSERT TG_SETTING VALUE(2,2,1,'\\\\192.168.11.88\会社共有（it）\\社内管理\Template','','','','');
INSERT TG_SETTING VALUE(2,3,1,'見積書','','','','');
INSERT TG_SETTING VALUE(2,3,2,'発注書','','','','');
INSERT TG_SETTING VALUE(2,3,3,'請求書','','','','');
INSERT TG_SETTING VALUE(2,3,4,'作業実績報告書','','','','');
INSERT TG_SETTING VALUE(3,1,1,'中国','','','','');
INSERT TG_SETTING VALUE(3,1,2,'日本','','','','');
INSERT TG_SETTING VALUE(3,1,3,'韓国','','','','');
INSERT TG_SETTING VALUE(3,1,4,'ベトナム','','','','');
INSERT TG_SETTING VALUE(3,1,5,'ミャンマー','','','','');
INSERT TG_SETTING VALUE(3,2,1,'1','','','','');
INSERT TG_SETTING VALUE(3,2,2,'3','','','','');
INSERT TG_SETTING VALUE(3,2,3,'5','','','','');
INSERT TG_SETTING VALUE(3,3,1,'日本国籍','','','','');
INSERT TG_SETTING VALUE(3,3,2,'永住者','','','','');
INSERT TG_SETTING VALUE(3,3,3,'技術・人文知識・国際業務','','','','');
INSERT TG_SETTING VALUE(3,3,4,'企業内転勤','','','','');
INSERT TG_SETTING VALUE(3,3,5,'日本人の配偶者等','','','','');
INSERT TG_SETTING VALUE(3,3,6,'永住者の配偶者等','','','','');
INSERT TG_SETTING VALUE(3,3,7,'定住者','','','','');
INSERT TG_SETTING VALUE(3,3,8,'その他','','','','');
INSERT TG_SETTING VALUE(3,4,1,'役員','','','','');
INSERT TG_SETTING VALUE(3,4,2,'総務','','','','');
INSERT TG_SETTING VALUE(3,4,3,'IT営業','','','','');
INSERT TG_SETTING VALUE(3,4,4,'ITエンジニア','','','','');
INSERT TG_SETTING VALUE(3,4,5,'不動産スタッフ','','','','');
INSERT TG_SETTING VALUE(3,4,6,'個人事業主','','','','');
INSERT TG_SETTING VALUE(3,5,1,'大学院（博士）','','','','');
INSERT TG_SETTING VALUE(3,5,2,'大学院（修士）','','','','');
INSERT TG_SETTING VALUE(3,5,3,'大学','','','','');
INSERT TG_SETTING VALUE(3,5,4,'短期大学','','','','');
INSERT TG_SETTING VALUE(3,5,5,'専門学校','','','','');
INSERT TG_SETTING VALUE(3,5,6,'高等学校','','','','');
INSERT TG_SETTING VALUE(3,5,7,'中学校','','','','');
INSERT TG_SETTING VALUE(3,5,8,'その他','','','','');
INSERT TG_SETTING VALUE(3,6,1,'DOS','','','','');
INSERT TG_SETTING VALUE(3,6,2,'Windows','','','','');
INSERT TG_SETTING VALUE(3,6,3,'Unix','','','','');
INSERT TG_SETTING VALUE(3,6,4,'Linux','','','','');
INSERT TG_SETTING VALUE(3,6,5,'andriod','','','','');
INSERT TG_SETTING VALUE(3,6,6,'IOS','','','','');
INSERT TG_SETTING VALUE(3,7,1,'C','','','','');
INSERT TG_SETTING VALUE(3,7,2,'ProC','','','','');
INSERT TG_SETTING VALUE(3,7,3,'C++','','','','');
INSERT TG_SETTING VALUE(3,7,4,'VC++','','','','');
INSERT TG_SETTING VALUE(3,7,5,'C#','','','','');
INSERT TG_SETTING VALUE(3,7,6,'C#.net','','','','');
INSERT TG_SETTING VALUE(3,7,7,'VB','','','','');
INSERT TG_SETTING VALUE(3,7,8,'VB.net','','','','');
INSERT TG_SETTING VALUE(3,7,9,'ASP','','','','');
INSERT TG_SETTING VALUE(3,7,10,'ASP.net','','','','');
INSERT TG_SETTING VALUE(3,7,11,'Java','','','','');
INSERT TG_SETTING VALUE(3,7,12,'JSP','','','','');
INSERT TG_SETTING VALUE(3,7,13,'PHP','','','','');
INSERT TG_SETTING VALUE(3,7,14,'HTML','','','','');
INSERT TG_SETTING VALUE(3,7,15,'XML','','','','');
INSERT TG_SETTING VALUE(3,7,16,'JavaScript','','','','');
INSERT TG_SETTING VALUE(3,7,17,'VBScript','','','','');
INSERT TG_SETTING VALUE(3,7,18,'Jquery','','','','');
INSERT TG_SETTING VALUE(3,7,19,'ProjectC','','','','');
INSERT TG_SETTING VALUE(3,7,20,'PL/SQL','','','','');
INSERT TG_SETTING VALUE(3,7,21,'Python','','','','');
INSERT TG_SETTING VALUE(3,7,22,'Shell','','','','');
INSERT TG_SETTING VALUE(3,7,23,'ABAP','','','','');
INSERT TG_SETTING VALUE(3,8,1,'Oracle','','','','');
INSERT TG_SETTING VALUE(3,8,2,'SQLServer','','','','');
INSERT TG_SETTING VALUE(3,8,3,'DB2','','','','');
INSERT TG_SETTING VALUE(3,8,4,'MySql','','','','');
INSERT TG_SETTING VALUE(3,8,5,'PostgreSQL','','','','');
INSERT TG_SETTING VALUE(3,8,6,'SQLite','','','','');
INSERT TG_SETTING VALUE(3,8,7,'Access','','','','');
INSERT TG_SETTING VALUE(3,8,8,'NoSQL','','','','');
INSERT TG_SETTING VALUE(3,8,9,'MongoDB','','','','');
INSERT TG_SETTING VALUE(3,9,1,'WebLogic','','','','');
INSERT TG_SETTING VALUE(3,9,2,'Apache ','','','','');
INSERT TG_SETTING VALUE(3,9,3,'IIS','','','','');
INSERT TG_SETTING VALUE(3,9,4,'LotusNotes','','','','');
INSERT TG_SETTING VALUE(3,10,1,'Struts','','','','');
INSERT TG_SETTING VALUE(3,10,2,'WebWork','','','','');
INSERT TG_SETTING VALUE(3,10,3,'Spring','','','','');
INSERT TG_SETTING VALUE(3,10,4,'Hibernate','','','','');
INSERT TG_SETTING VALUE(3,10,5,'Seasar2','','','','');
INSERT TG_SETTING VALUE(3,10,6,'Junit','','','','');
INSERT TG_SETTING VALUE(3,11,1,'Eclipse','','','','');
INSERT TG_SETTING VALUE(3,11,2,'.NET','','','','');
INSERT TG_SETTING VALUE(3,11,3,'Ultra Edit','','','','');
INSERT TG_SETTING VALUE(3,11,4,'Object Brower','','','','');
INSERT TG_SETTING VALUE(3,11,5,'PL/SQL Devloper','','','','');
INSERT TG_SETTING VALUE(3,11,6,'sql developer','','','','');
INSERT TG_SETTING VALUE(3,11,7,'Tomcat','','','','');
INSERT TG_SETTING VALUE(3,12,1,'銀行','','','','');
INSERT TG_SETTING VALUE(3,12,2,'証券','','','','');
INSERT TG_SETTING VALUE(3,12,3,'保険','','','','');
INSERT TG_SETTING VALUE(3,12,4,'物流','','','','');
INSERT TG_SETTING VALUE(3,12,5,'販売','','','','');
INSERT TG_SETTING VALUE(3,12,6,'生産管理','','','','');
INSERT TG_SETTING VALUE(3,12,7,'公共機関','','','','');
INSERT TG_SETTING VALUE(3,12,8,'医療・介護','','','','');
INSERT TG_SETTING VALUE(3,12,9,'教育機関','','','','');
INSERT TG_SETTING VALUE(3,12,10,'不動産','','','','');
INSERT TG_SETTING VALUE(3,12,11,'商社','','','','');
INSERT TG_SETTING VALUE(3,13,1,'PM','','','','');
INSERT TG_SETTING VALUE(3,13,2,'PMO','','','','');
INSERT TG_SETTING VALUE(3,13,3,'TL','','','','');
INSERT TG_SETTING VALUE(3,13,4,'PL','','','','');
INSERT TG_SETTING VALUE(3,13,5,'SE','','','','');
INSERT TG_SETTING VALUE(3,13,6,'PG','','','','');
INSERT TG_SETTING VALUE(3,13,7,'TESTER','','','','');
INSERT TG_SETTING VALUE(4,1,1,'20','','','','');
INSERT TG_SETTING VALUE(4,2,1,'25','','','','');
INSERT TG_SETTING VALUE(5,1,1,'30','','','','');
INSERT TG_SETTING VALUE(5,1,2,'35','','','','');
INSERT TG_SETTING VALUE(5,1,3,'40','','','','');
INSERT TG_SETTING VALUE(5,1,4,'45','','','','');